# site details
title: Sub Shaharan Coding
tag_line: a code journal
description: a simple coding blog for python, java and other interesting projects
keywords: python java blog
url: https://brainDeadCoder.github.io
author: Kacha Mukabe
author_url: http://twitter.com/a_doodlebug
#email_subscribe: http://eepurl.com/cNZfVz

# tech
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap