title:  Kacha Mukabe
tagline:  a minimalist coding blog
author:
  name: 'Kacha Mukabe'
  twitter:  kMukabe

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

google-ID: 'UA-106916188-1'

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Archive', url: 'archive.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/kachamukabe'}
- {icon: 'twitter', link: 'https://twitter.com/kMukabe'}
- {icon: 'instagram', link: 'https://instagram.com'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/kachamukabe/'}
- {icon: 'envelope', link: 'mailto:kmukabe@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
